### ISSUE TITLE
Version 2.0.0 breaks angular compile

### ISSUE THREAD

**Issue by Rhobal** [smart-table/smart-table-search#2]
With the update to smart-table-ng 0.0.10, I got search 2.0.0, but that doesn't run in ng serve.

I get the following error:

```
ERROR in ./node_modules/smart-table-search/dist/bundle/index.mjs
23:36-38 Can't import the named export 're' from non EcmaScript module (only default export is available)
```

I downgraded to core 2.3.1 and search 1.0.3, seems to work.

**Comment by lorenzofox3** [comment]
looks like you are using experimental ecmascript module on nodejs ?
You should probably use the typescript compiler. I don't see any issue on stackblitz and locally.  Anyway, I can't reproduce and it looks like it is a problem with your local setup I can't help with without more info

**Comment by Rhobal** [comment]
Thanks for checking! I deleted the node_modules entries and installed anew, now it works.
